// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVth0WfJzpOOO712dkb6NLdAl3gMWNGFA',
    appId: '1:860366274141:android:6cf25f5832eaf6d74c57b4',
    messagingSenderId: '860366274141',
    projectId: 'resonance-main-c75dd',
    storageBucket: 'resonance-main-c75dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp-4s5_8vrxWeDKH7qd4B0MEeH-xqpbFs',
    appId: '1:860366274141:ios:2003b896955c80fc4c57b4',
    messagingSenderId: '860366274141',
    projectId: 'resonance-main-c75dd',
    storageBucket: 'resonance-main-c75dd.firebasestorage.app',
    androidClientId:
        '860366274141-jav655fts215tiauar8qj6ojr2lfffpt.apps.googleusercontent.com',
    iosClientId:
        '860366274141-8klkp9m9a8o2av3ebou7ga07sj8kroj1.apps.googleusercontent.com',
    iosBundleId: 'com.resonance.app',
  );
}
